### ISSUE TITLE
cs_paint build fails with latest vulkan-sdk

### ISSUE THREAD

**Issue by gazzatav** [copperspice/cs_paint#5] opened 2019-11-17 14:54 UTC
I tried building the cs_paint demo on Ubuntu 18.04 after following the instructions to install the latest version - Edit: I gave the wrong vulkan-sdk version (Version: 1.1.106.0\~rc1-1lunarg18.04.1.1) 
I missed this later version in the `apt-cache show` output. Version: 1.1.126.0\~rc1-1lunarg18.04.1.1 is installed.
The cmake part was fine.  The build failure seems to be related to this issue [(https://github.com/KhronosGroup/Vulkan-Hpp/issues/289)].

The error message (with cs_paint path shortened) was:

`In file included from cs_paint/src/cspaint_context.h:30:0,
                 from cs_paint/src/cspaint_context.cpp:19:
/usr/include/vulkan/vulkan.hpp: In constructor ‘vk::ObjectDestroy<OwnerType, Dispatch>::ObjectDestroy(OwnerType, vk::Optional<const vk::AllocationCallbacks>, const Dispatch&) [with OwnerType = vk::Instance; Dispatch = vk::DispatchLoaderDynamic]’:
/usr/include/vulkan/vulkan.hpp:536:81: error: could not convert ‘vk::DispatchLoaderStatic()’ from ‘vk::DispatchLoaderStatic’ to ‘const vk::DispatchLoaderDynamic&’
     explicit UniqueHandle( Type const& value = Type(), Deleter const& deleter = Deleter() ) VULKAN_HPP_NOEXCEPT
                                                                                 ^~~~~~~~~
/usr/include/vulkan/vulkan.hpp: In constructor ‘vk::UniqueHandle<Type, Dispatch>::UniqueHandle(const Type&, const Deleter&) [with Type = vk::DebugReportCallbackEXT; Dispatch = vk::DispatchLoaderDynamic; vk::UniqueHandle<Type, Dispatch>::Deleter = vk::ObjectDestroy<vk::Instance, vk::DispatchLoaderDynamic>]’:
/usr/include/vulkan/vulkan.hpp:536:81: error: invalid initialization of reference of type ‘const vk::DispatchLoaderDynamic&’ from expression of type ‘vk::DispatchLoaderStatic’
In file included from cs_paint/src/cspaint_context.h:30:0,
                 from cs_paint/src/cspaint_context.cpp:19:
/usr/include/vulkan/vulkan.hpp:2588:7: note: in passing argument 3 of ‘vk::ObjectDestroy<OwnerType, Dispatch>::ObjectDestroy(OwnerType, vk::Optional<const vk::AllocationCallbacks>, const Dispatch&) [with OwnerType = vk::Instance; Dispatch = vk::DispatchLoaderDynamic]’
       ObjectDestroy( OwnerType owner = OwnerType(), Optional<const AllocationCallbacks> allocationCallbacks = nullptr, Dispatch const &dispatch = VULKAN_HPP_DEFAULT_DISPATCHER ) VULKAN_HPP_NOEXCEPT
       ^~~~~~~~~~~~~
cs_paint/src/cspaint_context.cpp:29:123: note:   when instantiating default argument for call to vk::UniqueHandle<Type, Dispatch>::UniqueHandle(const Type&, const Deleter&) [with Type = vk::DebugReportCallbackEXT; Dispatch = vk::DispatchLoaderDynamic; vk::UniqueHandle<Type, Dispatch>::Deleter = vk::ObjectDestroy<vk::Instance, vk::DispatchLoaderDynamic>]
 CsPaint::context::context(vk::Instance instance) : m_instance(instance), m_dynamicLoader(m_instance, vkGetInstanceProcAddr)`

Any advice welcome.

**Comment by agserm** [comment] 2019-11-17 19:16
Fantastic report, and good debugging info. We will take a look at reproducing this and let you know what we find out.

**Comment by gazzatav** [comment] 2019-11-17 22:58
I have since tried building with 
cmake -DVULKAN_HPP_DEFAULT_DISPATCHER=::vk::DispatchLoaderStatic\(\) path-to/cs_paint/

The object files for CsPaintDemo built but the linking failed with undefined references to vk::defaultDispatchLoaderDynamic in prototype.cpp

As before libCsPaint.so linked successfully.

I don't fully understand the relationship between all the dispatcher switch on/switch off defines yet but I hope that extra info helps pin it down.

**Comment by vdeurzen** [comment] 2019-11-19 19:50
@gazzatav could you try building with the SDK from this page: https://vulkan.lunarg.com/sdk/home#linux, the latest version is 1.1.126. I've used that version successfully on Arch Linux.

**Comment by gazzatav** [comment] 2019-11-19 21:11
@vdeurzen, do you mean using a tarball instead of installing the sdk via ubuntu packages?  That page is exactly where I followed the link to 1.1.126, went to Ubuntu packages and used the commands there to add a repo and install from that repo.  Maybe something has gone wrong in the installation. 

Edit: I do see 1.1.126 in the version string of the Ubuntu package.

Had a look in synaptic for installed vulkan components.  They all have 1.1.126 in the version string and now I see more in the  apt-cache show  output that I missed before, apologies - have updated original bug report, the version string is indeed Version: 1.1.126.0~rc1-1lunarg18.04.1.1.

**Comment by vdeurzen** [comment] 2019-11-22 17:56
Apologies for the slow reply, flue kept me away from my computer for a bit. We will have to dig into this a bit more to help you figure this out. I'm busy for the next few days, but will attempt to get a test docker container up and running as soon as I can.

If you find anything in the meantime, please let us know :-)

**Comment by gazzatav** [comment] 2019-11-23 22:51
No worries, glad you're feeling better now. Is there anything else you want me to try regarding the build?

**Comment by vdeurzen** [comment] 2019-12-02 11:46
@gazzatav I will try to set-up a docker image to reproduce your build, could you tell me whether you used any custom versions or settings other than the defaults for Ubuntu 18.04?

**Comment by gazzatav** [comment] 2019-12-04 17:15
It was an out of source build with no defines or options set as far as I
remember.  Ubuntu 18.04 updated of course.

**Comment by vdeurzen** [comment] 2019-12-05 14:10
I can consistently reproduce this issue on Arch, Gentoo and Ubuntu with the tarball and the package manager versions of the SDK. I think you are correct that there may have been another change in the API of Vulkan as you suggested initially. I will continue my investigation.

**Comment by gazzatav** [comment] 2019-12-05 14:11
Thanks, glad it's not just me!

**Comment by vdeurzen** [comment] 2019-12-05 15:52
It looks like the following commit, made just after the previous SDK version was released, adds a whole bunch of code for a DynamicDispatchLoader: https://github.com/KhronosGroup/Vulkan-Hpp/commit/48d540a23db87ff91e0ab698115cf1995ec37921

Adapting CsPaint to these changes will, I expect, take a bit of effort and time. For now you could consider using the previous version of the SDK: 1.1.121. I've built CsPaint successfully, in a Ubuntu docker container, using the tarball version of the 1.1.121 SDK and using the apt repository configuration.

Thank you once more for your report!

P.S. I will make sure the README is updated with the exact version information.

**Comment by gazzatav** [comment] 2019-12-06 00:56
Thanks for the update, I'll try the version you suggested.

**Comment by agserm** [comment] 2020-01-16 03:28
@gazzatav and @vdeurzen, can one or both of you try reproducing this with the test-sdk branch I just pushed? I believe that commit 8fe6889 will resolve this issue and allow compiling with both old and new SDK versions.

**Comment by vdeurzen** [comment] 2020-01-17 12:02
@agserm Awesome! It compiles without issues now. Ironically, the newest version of the vulkan SDK also solves the problem. I've tried all the combinations:

master with 1.1.121 compiles without problems :heavy_check_mark: 
master with 1.1.126: breaks, as discussed previously :warning: 
master with 1.1.130: compiles without problems :heavy_check_mark: 

test-sdk with 1.1.121: compiles without problems :heavy_check_mark: 
test-sdk with 1.1.126: compiles without problems :heavy_check_mark: 
test-sdk with 1.1.130: compiles without problems :heavy_check_mark:

**Comment by gazzatav** [comment] 2020-01-17 16:44
@agserm and @vdeurzen That's good news.  Thank you both for your work in fixing this.  I'm looking forward to trying this out.

**Comment by gazzatav** [comment] 2020-01-17 17:33
Everything built correctly including CsPaintDemo.  However, when I ran it I saw a window appear and then crash and had the following error message in the console:

```
○ → bin/CsPaintDemo 
VULKAN MESSAGE: setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config

VULKAN MESSAGE: setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.

Segmentation fault (core dumped)
```
I checked that I have a vulkan loader library installed:
```
libvulkan1 is already the newest version (1.1.126.0~rc1-1ubuntu18.04.1.1).
```
I did google the error but search results seemed to be user related.  I'm trying this at the moment on a Dell Vostro laptop.  I installed vulkan-utils (which removed vulkan-sdk-1.1.126 and vulkan-tools.  Running vulkan-info gave this output:
```
===========
VULKAN INFO
===========

Vulkan Instance Version: 1.1.70

/build/vulkan-UL09PJ/vulkan-1.1.70+dfsg1/demos/vulkaninfo.c:2700: failed with VK_ERROR_INITIALIZATION_FAILED
```
I feel like this is not in the scope of the original problem so feel free to close this issue but if you have any idea why I can't run CsPaintDemo I'd be grateful for a heads-up.
Thanks

**Comment by agserm** [comment] 2020-01-18 17:34
Thanks to both of you for testing and confirming this resolves the issue. I will merge and push the change shortly.

@gazzatav, I do agree that this latest problem is outside the scope of the current issue. I'm going to go ahead and close this one, but if you would open a new ticket with the output of `lspci -v` we can take a look and see why you might be having issues finding the correct Vulkan device.

**Closed as completed by agserm** 2020-01-18 17:34 UTC
